package com.example.demo.domain;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dmz_user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dmz_user.id
     *
     * @return the value of t_dmz_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dmz_user.id
     *
     * @param id the value for t_dmz_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }
}